[
  {
    "create_statement": "CREATE TABLE campaign_capture_byNova (id bigint NOT NULL, created_at timestamp with time zone NOT NULL DEFAULT now(), campaign text, summaryText text, missingFields text, sessionId uuid, userSessionID text, status text DEFAULT 'Created'::text);"
  },
  {
    "create_statement": "CREATE TABLE campaign_phases (id uuid NOT NULL DEFAULT gen_random_uuid(), campaign_id uuid, user_id text, name text, description text, phase_order integer, start_date timestamp with time zone, end_date timestamp with time zone, status text DEFAULT 'planned'::text, goals jsonb, target_metrics jsonb, created_at timestamp with time zone DEFAULT now(), updated_at timestamp with time zone DEFAULT now(), content_strategy text, recommended_content_types ARRAY DEFAULT '{}'::text[], recommended_platforms ARRAY DEFAULT '{}'::text[]);"
  },
  {
    "create_statement": "CREATE TABLE campaign_reports (id uuid NOT NULL DEFAULT gen_random_uuid(), campaign_id uuid, user_id text, report_type text DEFAULT 'campaign_plan'::text, report_title text, summary_text text, pdf_url text, pdf_generated_at timestamp with time zone, pdf_status text DEFAULT 'pending'::text, generated_by_ai boolean DEFAULT true, ai_model_version text DEFAULT 'Nova-1.0'::text, company_branding jsonb DEFAULT '{\"website\": \"www.priorityonetech.ca\", \"ai_credit\": \"Generated by AI developed by Priority One Tech Inc\", \"company_name\": \"Priority One Tech Inc\"}'::jsonb, download_count integer DEFAULT 0, last_downloaded_at timestamp with time zone, created_at timestamp with time zone DEFAULT now(), updated_at timestamp with time zone DEFAULT now());"
  },
  {
    "create_statement": "CREATE TABLE campaigns (id uuid NOT NULL DEFAULT gen_random_uuid(), user_id text, name text, description text, campaign_type text, status text DEFAULT 'draft'::text, start_date timestamp with time zone, end_date timestamp with time zone, created_at timestamp with time zone DEFAULT now(), updated_at timestamp with time zone DEFAULT now(), budget numeric(10,2) DEFAULT 0, target_audience jsonb, goals jsonb, target_metrics jsonb, platforms ARRAY DEFAULT '{}'::text[], total_reach integer DEFAULT 0, total_impressions integer DEFAULT 0, total_engagement integer DEFAULT 0, total_clicks integer DEFAULT 0, total_conversions integer DEFAULT 0, total_spent numeric(10,2) DEFAULT 0, number_of_phases integer DEFAULT 0, campaign_length text, summary_text text, created_by_ai boolean DEFAULT true, ai_model_version text DEFAULT 'Nova-1.0'::text);"
  },
  {
    "create_statement": "CREATE TABLE content (id uuid NOT NULL DEFAULT gen_random_uuid(), user_id text, campaign_id uuid, campaign_phase_id uuid, title text NOT NULL, description text, content_type text NOT NULL, text_content text, media_urls ARRAY, hashtags ARRAY, mentions ARRAY, platform_content jsonb, scheduled_date timestamp with time zone, published_date timestamp with time zone, status text DEFAULT 'draft'::text, platforms ARRAY NOT NULL, metrics jsonb, created_at timestamp with time zone DEFAULT now(), updated_at timestamp with time zone DEFAULT now());"
  },
  {
    "create_statement": "CREATE TABLE posts (id uuid NOT NULL DEFAULT gen_random_uuid(), user_id text, content_id uuid, campaign_id uuid, platform text NOT NULL, platform_post_id text, post_url text, likes integer DEFAULT 0, comments integer DEFAULT 0, shares integer DEFAULT 0, saves integer DEFAULT 0, reach integer DEFAULT 0, impressions integer DEFAULT 0, clicks integer DEFAULT 0, engagement_rate numeric(5,2) DEFAULT 0, metrics jsonb, published_at timestamp with time zone NOT NULL, last_updated timestamp with time zone DEFAULT now(), created_at timestamp with time zone DEFAULT now());"
  },
  {
    "create_statement": "CREATE TABLE profiles (id uuid NOT NULL, first_name text, last_name text, company text, role text DEFAULT 'user'::text, avatar_url text, created_at timestamp with time zone DEFAULT now(), updated_at timestamp with time zone DEFAULT now());"
  },
  {
    "create_statement": "CREATE TABLE raw_record (id bigint, created_at timestamp with time zone, campaign text, summaryText text, missingFields text, sessionId uuid, userEmail text);"
  },
  {
    "create_statement": "CREATE TABLE social_metrics (id uuid NOT NULL DEFAULT gen_random_uuid(), user_id uuid, platform text NOT NULL, metric_date date NOT NULL, followers_count integer DEFAULT 0, following_count integer DEFAULT 0, likes_count integer DEFAULT 0, comments_count integer DEFAULT 0, shares_count integer DEFAULT 0, saves_count integer DEFAULT 0, reach integer DEFAULT 0, impressions integer DEFAULT 0, profile_visits integer DEFAULT 0, website_clicks integer DEFAULT 0, story_views integer DEFAULT 0, story_replies integer DEFAULT 0, video_views integer DEFAULT 0, video_completion_rate numeric(5,2) DEFAULT 0, additional_metrics jsonb, created_at timestamp with time zone DEFAULT now(), updated_at timestamp with time zone DEFAULT now());"
  }
]